//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __GYROSCOPE_SIMULATOR_MAIN_H__
#define __GYROSCOPE_SIMULATOR_MAIN_H__

// USER CONSTANTS
// USER PROTOTYPES

extern uint8_t SPI0_TEMP_OUT_DATA_1;
extern uint8_t SPI0_TEMP_OUT_DATA_2;
extern uint8_t SPI0_GYRO_OUT2_DATA_1;
extern uint8_t SPI0_GYRO_OUT2_DATA_2;
extern uint8_t SPI0_GYRO_OUT_DATA_L;
extern uint8_t SPI0_GYRO_OUT_DATA_H;
extern uint8_t SPI0_SERIAL_NUM_DATA;
extern uint8_t SPI1_TEMP_OUT_DATA_1;
extern uint8_t SPI1_TEMP_OUT_DATA_2;
extern uint8_t SPI1_GYRO_OUT2_DATA_1;
extern uint8_t SPI1_GYRO_OUT2_DATA_2;
extern uint8_t SPI1_GYRO_OUT_DATA_L;
extern uint8_t SPI1_GYRO_OUT_DATA_H;
extern uint8_t SPI1_SERIAL_NUM_DATA;
extern bool SIN_COS;
extern int REZIM_3;
#endif

