//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __LCD_LIB_H__
#define __LCD_LIB_H__

// USER CONSTANTS
// USER PROTOTYPES
#define LCD_CLEARDISPLAY 0x01
#define LCD_RETURNHOME 0x02
#define LCD_ENTRYMODESET 0x04
#define LCD_DISPLAYCONTROL 0x08
#define LCD_CURSORSHIFT 0x10
#define LCD_FUNCTIONSET 0x20
#define LCD_SETCGRAMADDR 0x40
#define LCD_SETDDRAMADDR 0x80

// flags for display entry mode
#define LCD_ENTRYRIGHT 0x00
#define LCD_ENTRYLEFT 0x02
#define LCD_ENTRYSHIFTINCREMENT 0x01
#define LCD_ENTRYSHIFTDECREMENT 0x00

// flags for display on/off control
#define LCD_DISPLAYON 0x0C
#define LCD_DISPLAYOFF 0x08
#define LCD_CURSORON 0x0C
#define LCD_CURSOROFF 0x0E
#define LCD_BLINKON 0x00f
#define LCD_BLINKOFF 0x0C

// flags for display/cursor shift
#define LCD_DISPLAYMOVE 0x18
#define LCD_CURSORMOVE 0x14
#define LCD_MOVERIGHT 0x1C
#define LCD_MOVELEFT 0x18
// $[Mode Transition Prototypes]
extern void delay(int counts);
extern void LCD_WRITE(DIN);
extern void LCD_COMAND(DIN);
extern void LCD_SEND(DIN);
extern void LCD_Init();
