//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __ILI9481_LIB_H__
#define __ILI9481_LIB_H__
// USER CONSTANTS
// USER PROTOTYPES

#define TFTWIDTH  319
#define TFTHEIGHT 479


//DATA
extern int TFT_line, TFT_char,Text_size, Axis;
extern uint16_t Text_color;

extern void Write_8(DATA);
extern void Delay(S);

extern void ILI9481_init(void);
extern void writedata(DATA);

extern void setAddrWindow(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1);
extern void setRotation(int rotation);
extern void fillScreen(uint16_t color);
extern void drawPixel(int16_t x, int16_t y, uint16_t color);
extern void drawFastHLine(int16_t x, int16_t y, int16_t w, uint16_t color);
extern void drawFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color);
extern void printString(_char , uint16_t color);
extern void printChar (_char ,int16_t x, int16_t y, uint16_t color);
extern void TextSize( size );
extern void lcdPrintString(uint8_t *c);
extern void WriteDisplayBrightness(uint16_t Brightness);
extern void lcdOff();
extern void lcdOn();
extern void pulse();
extern uint16_t returnColor24_16(R , G , B);


extern void drawRoundRect(int x1, int y1, int x2, int y2, uint16_t color);
extern void drawRect(int x1, int y1, int x2, int y2, uint16_t color);
extern void drawRoundRect(int x1, int y1, int x2, int y2, uint16_t color);
extern void fillRect(int x1, int y1, int x2, int y2, uint16_t color);
extern void fillRoundRect(int x1, int y1, int x2, int y2, uint16_t color);
extern void drawCircle(int x, int y, int radius, uint16_t color);
extern void fillCircle(int x, int y, int radius, uint16_t color);
//extern void _fast_fill_16(int ch, int cl, long pix);


extern void LCD_Writ_Bus(ch,cl);
extern void LCD_Write_DATA(VH,VL);
extern void LCD_Write_COM(VL);

#endif

